# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jM7TQemuC6n_snDxNwuafp7dU0oCTL6a
"""

import streamlit as st
import os

# Get the current working directory where the Streamlit app is running
current_directory = os.getcwd()

st.title("Download Files")
if st.button("Download"):
  # Get a list of all files in the current directory
  file_list = os.listdir(current_directory)

  # Create a section to download files
  for file in file_list:
      file_path = os.path.join(current_directory, file)
      with open(file_path, "rb") as file_content:
          st.download_button(label=f"Download {file}", data=file_content, key=file)